### ISSUE TITLE
AccessPort Port name cannot show COM1

### ISSUE THREAD

**Issue by davidchik** [zshorz/AccessPort#2]
在串口选择什么选项都没有，我尝试把第38行改为
    g_mySerialPort->setPortName("COM1");
但是执行时还是什么选项都没有。
你认为是什么原因呢？
谢谢。

**Comment by kirito41dd** [comment]
看这里的代码，程序初始化时候会先获取系统可用的port，将其名字放入选择框
```cpp
void MainWindow::init()
{
    // 添加所有串口到comboBox
    foreach (const QSerialPortInfo &info, QSerialPortInfo::availablePorts()) {
        ui->comboBox_COMx->addItem(info.portName());
    }
```
如果系统可用port里没COM1, 你强行将它添加进去是没有用的

建议你详细关注下 `QSerialPortInfo::availablePorts()`函数的返回

应该是这里没有获取到任何可用port
